addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      - ant-optional

language: java
jdk: openjdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
